import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
import AuthProvider from "@/context/AuthContext";
import NextAuthProvider from "@/components/NextAuthProvider";
import Layouts from "@/components/Layouts";
import Slidebar from "@/components/Slidebar";
import LayoutProvider from "@/context/LayoutContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "coffee dashboard",
  description: "Generated by coffee dashboard",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <NextAuthProvider>
          <AuthProvider>
            <LayoutProvider>{children}</LayoutProvider>
          </AuthProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
