import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "@/context/AuthContext";
import NextAuthProvider from "@/components/NextAuthProvider";
import LayoutProvider from "@/context/LayoutContext";
import LoadingProgress from "@/components/LoadingProgress";
import DataProvider from "@/context/DataContext";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "coffee dashboard",
  description: "Generated by coffee dashboard",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <NextAuthProvider>
          <AuthProvider>
            <DataProvider>
              <LayoutProvider>
                <LoadingProgress>{children}</LoadingProgress>
              </LayoutProvider>
            </DataProvider>
          </AuthProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
